Fix variable scope
It seems in julia 1.10, the variable needs to be declared outside of the
`try`/`if` block, otherwise it complains

```julia
ERROR: LoadError: UndefVarError: `format` not defined
```